
import { Question, TourStep } from './types';

export const interviewQuestions: Question[] = [
    {
        text: "Tell me about a time you had to handle a challenging project. What was the situation, what actions did you take, and what was the result?",
        keywords: [
            "Collaborated", "Improved", "Resolved", "Learned", "Challenge", "Ownership", "Impact"
        ],
        requirements: [
            { id: 'star-s', text: 'Situation: Describe the specific challenge or project.', linkedKeywords: ['Challenge'] },
            { id: 'star-t', text: 'Task: Explain your exact responsibility and goal.', linkedKeywords: ['Ownership'] },
            { id: 'star-a', text: 'Action: Detail the steps you took to address it.', linkedKeywords: ['Collaborated', 'Improved', 'Resolved'] },
            { id: 'star-r', text: 'Result: Share the final outcome and what you learned.', linkedKeywords: ['Impact', 'Learned'] },
        ]
    },
    {
        text: "Describe a situation where you had to work with a difficult team member. How did you handle it and what was the outcome?",
        keywords: [
            "Teamwork", "Conflict", "Collaboration", "Empathy",
            "Communication", "Resolved", "Negotiated", "Productive",
            "Positive Outcome", "Professionalism", "Shared Goal", "Feedback"
        ],
        requirements: [
            { id: 'conflict-s', text: 'Situation: Describe the team context and the conflict.', linkedKeywords: ['Teamwork', 'Conflict'] },
            { id: 'conflict-t', text: 'Task: Explain your goal in resolving the friction.', linkedKeywords: ['Professionalism'] },
            { id: 'conflict-a', text: 'Action: Detail how you communicated and collaborated.', linkedKeywords: ['Communication', 'Empathy', 'Negotiated'] },
            { id: 'conflict-r', text: 'Result: Summarize the positive impact on the team.', linkedKeywords: ['Resolved', 'Productive', 'Positive Outcome', 'Shared Goal'] },
        ]
    }
];

export const tourSteps: TourStep[] = [
    // --- WELCOME PHASE ---
    {
        id: 'welcome-1-header',
        targetId: 'welcome-header',
        title: 'Welcome to Ascend!',
        content: "This quick tour will walk you through customizing your interview experience. Your settings are saved and restored after the tour.",
        placement: 'bottom',
        component: 'welcome',
        section: 'welcome',
    },
    {
        id: 'welcome-2-mode',
        targetId: 'welcome-mode-selection',
        title: 'Choose Your Path',
        content: 'Select "Practice with Ascend" for a CV-tailored experience, or "Direct Job Search" for a standard focused approach.',
        placement: 'bottom',
        component: 'welcome',
        section: 'mode',
    },
    {
        id: 'welcome-3-audio',
        targetId: 'welcome-audio-cues',
        title: 'Audio Assistance',
        content: 'Enable the Audio Guide to have setup options read aloud as you hover over them. Great for focus and accessibility.',
        placement: 'bottom',
        component: 'welcome',
        section: 'audio',
    },
    {
        id: 'welcome-4-nda',
        targetId: 'welcome-nda-agreement',
        title: 'Legal & Privacy',
        content: 'Please review and accept our NDA to ensure a secure and confidential practice environment.',
        placement: 'top',
        component: 'welcome',
        section: 'nda',
    },
    {
        id: 'welcome-5-timer',
        targetId: 'welcome-timer-display',
        title: 'Time Awareness',
        content: 'Choose how you want to track time. We recommend a style based on how you handle pressure.',
        placement: 'top',
        component: 'welcome',
        section: 'timer',
    },
    {
        id: 'welcome-6-accessibility',
        targetId: 'welcome-accessibility',
        title: 'Easy-to-Read Font',
        content: 'Use our structural font adjustment (Verdana) for improved legibility during your session.',
        placement: 'top',
        component: 'welcome',
        section: 'accessibility',
    },
    {
        id: 'welcome-7-setup',
        targetId: 'welcome-standard-jd',
        title: 'Standard Practice Setup',
        content: "Fill in the company and role details, and upload your CV to generate highly relevant practice questions.",
        placement: 'top',
        component: 'welcome',
        section: 'setup',
    },
    {
        id: 'welcome-8-start',
        targetId: 'welcome-start-button',
        title: "You're All Set!",
        content: "Once you're ready, click here to begin your session. Good luck!",
        placement: 'top',
        component: 'welcome',
        section: 'start',
        action: 'START_INTERVIEW',
    },

    // --- INTERVIEW PHASE ---
    {
        id: 'interview-1-layout',
        targetId: 'ascend-platform-layout',
        title: 'Interview Command Center',
        content: "Welcome to the simulation environment. This space is designed to replicate high-stakes interview conditions while providing cognitive support.",
        placement: 'bottom',
        component: 'interview',
        section: 'intro',
    },
    {
        id: 'interview-2-timer',
        targetId: 'ascend-timer-module',
        title: 'Time Awareness Module',
        content: "We provide three psychological framing conditions: ELAPSED (Standard), DURATION (Urgency), and USED (Efficiency). Research shows different timers affect performance based on your pressure tolerance.",
        placement: 'right',
        component: 'interview',
        section: 'timer',
    },
    {
        id: 'interview-3-video-toggle',
        targetId: 'ascend-video-toggle',
        title: 'Visual Load Management',
        content: "Experience 'Zoom Fatigue'? Use this toggle to hide your self-view. This reduces cognitive load, allowing you to focus entirely on your verbal logic.",
        placement: 'left',
        component: 'interview',
        section: 'video',
    },
    {
        id: 'interview-4-phase',
        targetId: 'ascend-phase-indicators',
        title: 'STAR Phase Tracking',
        content: "These indicators track your progress through the Situation, Task, Action, and Result phases. It ensures your logic remains structured and impactful.",
        placement: 'bottom',
        component: 'interview',
        section: 'logic',
    },
    {
        id: 'interview-5-toolkit',
        targetId: 'ascend-toolkit-sidebar',
        title: 'Supportive Toolkit',
        content: "On the right, you'll find real-time support tools: an interactive Plan (STAR checklist), a Live Transcript for verbal monitoring, and the AI Analysis pipeline.",
        placement: 'left',
        component: 'interview',
        section: 'toolkit',
    },
    {
        id: 'interview-5-star',
        targetId: 'ascend-toolkit-star',
        title: 'Dynamic Practice Plan',
        content: "This real-time checklist monitors your response. As you answer, the system automatically marks off Situation, Task, Action, and Result phases to ensure your logic is complete.",
        placement: 'left',
        component: 'interview',
        section: 'star',
    },
    {
        id: 'interview-6-record',
        targetId: 'ascend-record-button',
        title: 'Capturing Your Response',
        content: "When you start speaking, our high-fidelity transcription engine begins mapping your answer against professional rubrics in real-time.",
        placement: 'top',
        component: 'interview',
        section: 'record',
    },
    {
        id: 'interview-7-process',
        targetId: 'ascend-next-step-button',
        title: 'Process vs. Progression',
        content: '"Next Step" moves you through the STARS checklist for your current answer. Use the "Arrow" next to it only if you want to skip to the next question entirely.',
        placement: 'top',
        component: 'interview',
        section: 'process',
    },

    // --- PROBING & BREAK ---
    {
        id: 'probing-1-analysis',
        targetId: 'ascend-probing-pipeline',
        title: 'Deep Domain Analysis',
        content: "During the Probing phase, our AI analyzes your response for coherence and depth. If it detects gaps, it generates targeted 'Level 2' follow-up questions.",
        placement: 'left',
        component: 'interview',
        section: 'probing',
    },
    {
        id: 'probing-2-manual',
        targetId: 'ascend-deep-probe-button',
        title: 'AI Probing vs. Moving On',
        content: 'Use "Deep Probe" to manually challenge yourself with a follow-up question. Use "Move On" in the sidebar if you are satisfied with your response depth.',
        placement: 'bottom',
        component: 'interview',
        section: 'probing',
    },
    {
        id: 'toolkit-reports-1',
        targetId: 'ascend-toolkit-reports',
        title: 'Immediate Response Feedback',
        content: "After each answer, you receive an immediate 'Flash Report' here. It summarizes your strengths and identifies exactly where you can deepen your next response.",
        placement: 'left',
        component: 'interview',
        section: 'reports',
    },
    {
        id: 'break-1-reflect',
        targetId: 'reflective-break-content',
        title: 'Reflective Break',
        content: "Between questions, we enforce an intentional 2-minute pause. This 'Cognitive Cooling' period is crucial for mental reset and structural planning of your next answer.",
        placement: 'top',
        component: 'interview',
        section: 'break',
    },
    // --- REPORT PHASE ---
    {
        id: 'report-1-header',
        targetId: 'report-header',
        title: 'Performance Intelligence Report',
        content: "At the end of your session, we generate a comprehensive audit of your performance across multiple professional dimensions.",
        placement: 'bottom',
        component: 'report',
        section: 'header',
    },
    {
        id: 'report-2-summary',
        targetId: 'report-performance-summary',
        title: 'Executive Summary',
        content: "This section provides a high-level synthesis of your strengths and areas for growth, identifying recurring patterns in your communication style.",
        placement: 'top',
        component: 'report',
        section: 'summary',
    },
    {
        id: 'report-3-rubrics',
        targetId: 'report-rubrics-grid',
        title: 'Professional Rubrics',
        content: "We score your response according to 5 core factors: STAR Alignment, Professionalism, Action-Orientedness, Result Focus, and Contextual Clarity.",
        placement: 'top',
        component: 'report',
        section: 'rubrics',
    },
    {
        id: 'report-4-chc',
        targetId: 'report-chc-clusters',
        title: 'McGrew (2009) CHC Clusters',
        content: "Our most advanced metric. It deconstructs your performance into Knowledge (Gc), Reasoning (Gf), and Performance (Gq) dimensions, mapping your cognitive merit.",
        placement: 'top',
        component: 'report',
        section: 'chc',
    },
    {
        id: 'report-5-insights',
        targetId: 'report-actionable-insights',
        title: 'Actionable Insights',
        content: "Finally, we provide prioritized instructions for your next session. Focus on these to see the fastest improvement in your interview scores.",
        placement: 'top',
        component: 'report',
        section: 'finish',
    }
];
